Section 1: Pandas: A Data Analyst's Best Friend
Exercise Set 1: Viewing Data

In [ ]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

In [7]:
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

In [8]:
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

In [10]:
df.shape

(20, 4)

Exercise Set 2: Indexing with .loc[] and .iloc[]

In [11]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [16]:
df.loc[12, ['Name', 'Age']]
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [17]:
df.loc[(df["Pclass"] == 1) & (df["Sex"] == "female")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [18]:
df.iloc[9]["Age"]

np.float64(14.0)

In [19]:
df.loc[100:105, ["Fare", "Survived"]]

        Fare  Survived
100   7.8958         0
101   7.8958         0
102  77.2875         0
103   8.6542         0
104   7.9250         0
105   7.8958         0

Exercise Set 3: Summary Tools

In [31]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

df.describe()
df.head()
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df["Embarked"].value_counts()

In [32]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [33]:
df["Age"].mean()

np.float64(29.69911764705882)

In [34]:
df["Fare"].max()
df["Name"].nunique()

891

In [35]:
df["Sex"].value_counts()
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

Section 2: Clean & Tidy Data
Exercise Set 1: Dropping Data

In [36]:

import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

In [37]:
df_no_email = df.drop("Email", axis=1)

In [38]:
df.drop(2, inplace=True)

In [39]:
df = df.drop(["City", "Email"], axis=1)

In [40]:
df_trimmed = df.drop([0, 3])

In [41]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30
3  David   40

Exercise Set 2: Missing Data

In [42]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [43]:
df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [44]:
df.isna()
df.isna().sum()

Name    0
Age     2
City    1
dtype: int64

In [45]:
df.dropna()

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

In [46]:
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [47]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [50]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df.head()

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000     NaN
3    David  40.000000   Miami
4      Eva  33.333333  Boston

Exercise Set 3: Duplicates

In [56]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [57]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [58]:
df.drop_duplicates()

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

In [59]:
df.drop_duplicates(keep="last")

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [60]:
df.drop_duplicates(keep=False)

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

In [61]:
df.head()

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA

Section 3: Data Wrangling Essentials
Exercise Set 1: Renaming Columns

In [62]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [63]:
df.rename(columns={
    "fname": "FirstName",
    "lname": "LastName"
})

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [65]:
df.columns = ["FirstName", "LastName", "Country"]
df.head()

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

Exercise Set 2: Reordering Columns

In [70]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)
df.head()

      Name     Dept    Sal
0    Alice       HR  60000
1      Bob  Finance  70000
2  Charlie       IT  80000

In [67]:
df = df.rename(columns={
    "Dept": "Department",
    "Sal": "Salary"
})

In [68]:
df = df[["Salary", "Name", "Department"]]

In [69]:
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

Exercise Set 3: GroupBy and Agg

In [71]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [72]:
df.groupby("Store").agg({
    "Sales": "mean",
    "Profit": "mean"
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [73]:
df.groupby("Product").agg({
    "Sales": "max",
    "Profit": "min"
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

In [74]:
df.groupby("Store").agg(
    Avg_Sales=("Sales", "mean"),
    Max_Profit=("Profit", "max")
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

In [77]:
df.groupby(["Store", "Product"]).agg({
    "Sales": "sum"
})

df.head()

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

Exercise Set 4: Joining

In [78]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

In [79]:
df_customers.join(df_orders)

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [80]:
df_cities = pd.DataFrame({
    "City": ["NYC", "LA", "Chicago"]
}, index=[101, 102, 103])